board_cards:
  - 0.369
  - 0.449
  - 0.24
  - 0.06
  - 0
hand_cards:
  card1:
  - 0.537
  - 0.668
  - 0.04
  - 0.11
  - -3
  card2:
  - 0.584
  - 0.682
  - 0.029
  - 0.094
  - 13
ocr:
  language: eng
  oem: 3
  psm: 6
scan_interval: 1000
window_title:
- Poker Fate
