board_cards:
  pos:
    - 0.378
    - 0.452
  size:
    - 0.255
    - 0.052
hand_cards:
  card1:
    pos:
      - 0.546
      - 0.693
    size:
      - 0.028
      - 0.077
    r: -4
  card2:
    pos:
      - 0.587
      - 0.687
    size:
      - 0.028
      - 0.077
    r: 12
ocr:
  language: eng
  oem: 3
  psm: 6
scan_interval: 1000
window_title:
  - Poker Fate
