board_cards:
  pos:
  - 0.379
  - 0.437
  size:
  - 0.255
  - 0.050
hand_cards:
  card1:
    pos:
    - 0.546
    - 0.688
    r: -4
    size:
    - 0.028
    - 0.076
  card2:
    pos:
    - 0.587
    - 0.683
    r: 10.3
    size:
    - 0.028
    - 0.076
ocr:
  oem: 2
scan_interval: 500
window_title:
- Poker Fate
